<a href="https://colab.research.google.com/github/MiguelAngel-ht/Quantum-Computing/blob/main/Optimized_Partial_Trace_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
v1 = np.array([[1,0]])
v2 = v1.T

In [ ]:
print(v1)
print(v2)

[[1 0]]
[[1]
 [0]]


In [ ]:
def otimes(A,B):
  N1 = np.array(np.shape(A))
  N2 = np.array(np.shape(B))

  C = np.zeros(N1*N2)

  for i in range(N1[0]):
    for j in range(N1[1]):
      for k in range(N2[0]):
        for l in range(N2[1]):
          C[N2[0]*(i)+k][N2[1]*(j)+l] = A[i][j]*B[k][l]
  return C



In [ ]:
from datetime import datetime

In [ ]:
start_time = datetime.now()

print(otimes(v1,v2))

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))
# np.kron()

[[1. 0.]
 [0. 0.]]
Duration: 0:00:00.000812


In [ ]:
start_time = datetime.now()

print(np.kron(v1,v2))

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

[[1 0]
 [0 0]]
Duration: 0:00:00.000534


In [56]:
def partial_trace0(A,base):     # ORIGINAL FUNCTION
  
  n = int(len(A)/base)
  ptrA = np.full((n,n),0)
  v = np.identity(base).reshape(base,base,1)   # (n,n,1) is for operations of matrix
  I = np.identity(n)

  try:
    for i in range(base):
      b = otimes(v[i],I)
      ptrA = ptrA + np.matmul(np.matmul(b.T,A),b)
  except:
    print('The operation is not possible')

  return ptrA

In [65]:
def partial_trace1(A,base):   # MOST ELEGANT AND FASTER FUNCTION
  
  n = int(len(A)/base)
  ptrA = np.zeros((n,n))
  v = np.eye(base).reshape(base,base,1)   # (n,n,1) is for operations of matrix
  I = np.eye(n)

  try:
    for i in range(base):
      b = np.kron(v[i],I)
      ptrA += (b.T@A)@b
  except:
    print('The operation is not possible')

  return ptrA

In [66]:
A = np.random.randint(0,2,(10,10))

In [67]:
start_time = datetime.now()

print(partial_trace0(A,5))

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

[[3. 2.]
 [2. 2.]]
Duration: 0:00:00.003254


In [68]:
start_time = datetime.now()

print(partial_trace1(A,5))

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

[[3. 2.]
 [2. 2.]]
Duration: 0:00:00.002211
