<a href="https://colab.research.google.com/github/MiguelAngel-ht/Quantum-Computing/blob/main/OTIMES_function_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
v1 = np.array([[1,0]])
v2 = v1.T

In [ ]:
print(v1)
print(v2)

[[1 0]]
[[1]
 [0]]


In [ ]:
def otimes(A,B):
  N1 = np.array(np.shape(A))
  N2 = np.array(np.shape(B))

  C = np.zeros(N1*N2)

  for i in range(N1[0]):
    for j in range(N1[1]):
      for k in range(N2[0]):
        for l in range(N2[1]):
          #print(N2[1]*(i)+k,N2[]*(j)+l)
          C[N2[0]*(i)+k][N2[1]*(j)+l] = A[i][j]*B[k][l]
  return C



In [ ]:
N1 = np.array(np.shape(v1))
N2 = np.array(np.shape(v3))
C = np.zeros(N1*N2)
C

array([[0., 0., 0., 0.]])

In [ ]:
print(otimes(v1,v2))

[[1. 0.]
 [0. 0.]]
