<a href="https://colab.research.google.com/github/MiguelAngel-ht/Quantum-Computing/blob/main/Partial_Trace_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([[1,0]])
v2 = v1.T

In [3]:
print(v1)
print(v2)

[[1 0]]
[[1]
 [0]]


In [4]:
def otimes(A,B):
  N1 = np.array(np.shape(A))
  N2 = np.array(np.shape(B))

  C = np.zeros(N1*N2)

  for i in range(N1[0]):
    for j in range(N1[1]):
      for k in range(N2[0]):
        for l in range(N2[1]):
          #print(N2[1]*(i)+k,N2[]*(j)+l)
          C[N2[0]*(i)+k][N2[1]*(j)+l] = A[i][j]*B[k][l]
  return C



In [5]:
print(otimes(v1,v2))

[[1. 0.]
 [0. 0.]]


In [6]:
def partial_trace(A,base):
  
  n = int(len(A)/base)
  ptrA = np.full((n,n),0)
  v = np.identity(base).reshape(base,base,1)   # (n,n,1) is for operations of matrix
  I = np.identity(n)

  try:
    for i in range(base):
      ptrA = ptrA + np.matmul(np.matmul(otimes(v[i],I).T, A), otimes(v[i],I))
  except:
    print('The operation is not possible')

  return ptrA

In [7]:
A = np.full((6,6),0)
for i in range(6):
  for j in range(6):
    A[i][j] = np.random.randint(0,2)

partial_trace(A,3)

array([[1., 2.],
       [1., 1.]])