[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1iw3Zub-o5mAAklB4oew5v4VHiOauA0bH?usp=sharing)

In [4]:
import numpy as np

In [5]:
v1 = np.array([[1,0]])
v2 = v1.T

In [6]:
print(v1)
print(v2)

[[1 0]]
[[1]
 [0]]


In [21]:
def otimes(A,B):
  N1 = np.array(np.shape(A))
  N2 = np.array(np.shape(B))

  C = np.zeros(N1*N2)

  for i in range(N1[0]):
    for j in range(N1[1]):
      for k in range(N2[0]):
        for l in range(N2[1]):
          #print(N2[1]*(i)+k,N2[]*(j)+l)
          C[N2[0]*(i)+k][N2[1]*(j)+l] = A[i][j]*B[k][l]
  return C



In [64]:
print(otimes(v1,v2))

[[1. 0.]
 [0. 0.]]


In [67]:
def partialTrace(A,No_base):
  
  n = int(len(A)/No_base)
  ptrA = np.zeros((n,n))
  u = np.identity(No_base).reshape(No_base,No_base,1)
  I = np.identity(n)

  for i in range(No_base):
    product2 = otimes(u[i],I)
    product1 = product2.T
    ptrA = ptrA + np.matmul(np.matmul(product1, A), product2)

  return ptrA

In [68]:
A = np.random.randint(4, size=(6,6))
print(A)
print(partialTrace(A,2))

[[0 0 0 0 3 0]
 [3 1 1 2 0 0]
 [3 2 2 0 1 3]
 [3 0 0 2 0 3]
 [0 1 1 1 0 2]
 [0 2 2 3 1 0]]
[[2. 0. 3.]
 [4. 1. 3.]
 [6. 3. 2.]]
